- README.md
- data/gen_embeddings.py
I wasn't super sure if we need to include these in the README. But if we do I added them. If not, then pls ignore!
- installing requirements.txt
- installing spacy and how to pickle embeddings
- description of CLI flags
> New sections

- utils/questions.py
Metric was an artifact of an old experiment. Removing it from the codebase
> Removed unneeded `fuzzy_correct`

- data/questions_gen.csv
Remove length from geography query as it's not needed by the question
> Update gold query

- query_generators/openai.py
> Fixed a bug for evaluating OpenAI models, where the seed parameter was not passed to the API

- prompts/prompt.md
Updated prompt used for 7b sota results. This uses the alpaca format and repeats the question at the start and the end.
> Updated prompt

- query_generators/openai.py
Added `user_question` to assistant prompt for completeness
> Update openai.py generator

- eval/hf_runner.py
- main.py
- requirements.txt
- make `vllm` conditional based on the platform in requirements.txt file
- update `eval/hf_runner.py` to use `mps` if it's available
- update `eval/hf_runner.py` to call different `empty_cache` & `synchronize` based on devise
- update the error message in `main.py`
> Add support to MPS backend

- eval/hf_runner.py
1. Use the try-except approach to detect if the model supports beam_search
2. Use traceback to check the stack to confirm this Error is relevant to beam_search
3. Raise an error if others
close #61
> force num_beams to 1 if beam search is not supported

- README.md
Add api server instructions based on learning [here](https://defog-ai.slack.com/archives/C055F52RR2A/p1706835602878459)
> Add api server instructions

- README.md
- eval/api_runner.py
- eval/hf_runner.py
- eval/llama_cpp_runner.py
- eval/mistral_runner.py
- eval/mlx_runner.py
- eval/openai_runner.py
- main.py
- requirements.txt
Mistral models are now supported, though with a hard-coded prompt. The promptfile provided is currently ignored
> Added support for Mistral models

- README.md
- eval/anthropic_runner.py
- eval/api_runner.py
- eval/gemini_runner.py
- eval/hf_runner.py
- eval/llama_cpp_runner.py
- eval/mistral_runner.py
- eval/mlx_runner.py
- eval/openai_runner.py
- eval/vllm_runner.py
- main.py
- prompts/prompt_gemini.md
- prompts/prompt_mistral.md
- query_generators/anthropic.py
- query_generators/openai.py
- query_generators/query_generator.py
- utils/gen_prompt.py
- utils/questions.py
- Added new prompt parameters for error correction in all the runners.
- Brought the standard `generate_prompt` function into the utils.
- Created new prompt files in the `prompts` folder for gemini and mistral instead of hardcoding them in the runners.
- Added instructions for gemini and mistral setup.
> New prompts

- data/questions_gen_postgres.csv
- tests/test_utils_pruning.py
- utils/pruning.py
- Fixed bug in get_md_emb which would previously result in duplicate columns in the table metadata string
- Added a test for the above
- Removed backticks in the join list since we no longer have backticks in our prompt template
- Clarified a few questions/queries in questions_gen
> Fix pruning function

- README.md
- gcs_eval.py
- utils/api_server.py
Added custom api server that only returns the generated output but not the prompt to simplify the output parsing. Updated `README.md` with instructions.
Updated `gcs_eval.py` with option to set `NUM_BEAMS` in 1 place.
> Added custom api server

- README.md
- eval/api_runner.py
- prompts/prompt.md
- utils/questions.py
- add temperature 0 to api server
- bring back ability to use api server for something that's not vllm or tgi
- update recommended prompt
- update instruction formatting
> Update API runner and prompt

- auto_error_analysis.ipynb
Added a new notebook for generating summaries of db exec errors and logical errors found in result files of a single train dataset. These summaries provide users with a better understanding of the areas in which the training dataset can be improved.
> New nb for automated error analysis

- eval/vllm_runner.py
Standardize prompt formatting in vllm by tokenizing the prompt completely first, and checking if the bos token is already at the start and then adding it if not. Also learnt that vllm allows us to pre-tokenize and pass in the token_id's instead of the string as it allows us to control special tokens more consistently from our side. Tested on a bunch of checkpoints and it generally does equal or slightly better.
> Standardize prompt formatting for vllm

- run_checkpoints.sh
This is to have more consistency with results expected in a production scenario
> Update run_checkpoints.sh to use the vllm api server instead of offline inference

- eval/api_runner.py
- main.py
- utils/api_server.py
Please refer to https://github.com/defog-ai/eval-visualizer/ for details on how this can be used to visualized sql-eval
> Added ability to get logprobs from vllm API results, and see them visualized in another repo

- run_checkpoints.sh
- run_checkpoints_cot.sh
add `--logprobs` option to sql eval command in both run scripts
> add logprobs option to sql eval command

- eval/api_runner.py
- run_checkpoints_adapters.sh
- Add script that preprocesses LoRA adapters by dropping base layer weights, then runs sql-eval on every checkpoint using the adapters
- Minor: shifted print statement in api_runner
> Eval script for vLLM LoRA

- analyze_results_and_post_to_slack.py
Modified code to facet by cot inference, and allow graphs of different models to overlay each other.
> Modify result plots in slack
