utils/pruning.py

Previously, we used to get a warning about tokenizers_parallelism not being set. Eg:
```
-o results/my_query_generator.csv \
-g oa \
-f prompts/prompt.md \
-m gpt-3.5-turbo-0613 \
-n 1 \
-p 5 \
-v
preparing questions...
0%|                                                                                                                                                                  | 0/1 [00:00<?, ?it/s]huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
- Avoid using `tokenizers` before the fork if possible
- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: …
```

Set TOKENIZERS_PARALLELISM if not set

---

CONTRIBUTING.md
README.md
main.py

updated README.md and CONTRIBUTING.md with relative links to code in repo.
updated runner to only set default model for `oa` instead of all model_type's to avoid silent failures where `hf` uses the default model when unspecified. now the error should appear up front in the args when it isn't set when using `hf`, which is a lot less verbose and clearer:
```
$ python -W ignore main.py \
-o results/results.csv \
-g hf \
-f prompts/prompt.md
Traceback (most recent call last):
File "/Users/jp/workspace/sql-eval/main.py", line 27, in <module>
raise ValueError(
ValueError: Model must be specified for HF model type. See section on CLI flags in README.md for more details.
```

Updated documentation

---

eval/eval.py
eval/hf_runner.py

This PR does 2 main things
**1. Fixing the `GROUP BY {}` bug that was affecting all queries**
Our `get_all_minimal_queries` function that dynamically updates `GROUP BY` statements currently expects a single space between the `GROUP BY` and curly braces (`{}`)
```python
if right.find("GROUP BY {}"):
right = right.replace("GROUP BY {}", f"GROUP BY {column_str}")
```
However, if a query has something like `GROUP BY    {}`, this will not replace the query.
With this in view, we now reformat the query at the beginning of a function like this:
```python
query = " ".join(
query.split()
)  # replace multiple whitespaces with single space to avoid errors
```
**2. Adding better support for Llama-2 based models**
We now use the `LlamaForCausalLM` and `LlamaTokenizer` classes instead of …

Main fix: updating the `get_all_minimal_queries` function to avoid errors

---

utils/pruning.py

The problem is that the query_emb was of shape 384 previously, and we need to add an additional dimension to it to make it (1, 384). This requirement came into being in torch 2.1 (backwards compatible with torch 2.0 also).

This commit fixes #32

---

README.md
eval/hf_runner.py
main.py
utils/pruning.py

- We now allow users to pass in a boolean flag from the cli args down through to prune_metadata_str to allow the selection of a private data library for evaluations. The flag defaults to True, which means defog-data is used by default.
- Added instructions for how to incorporate private data.

 Add support for private data

---

.gitignore
README.md
eval/hf_runner.py
eval/openai_runner.py
main.py
query_generators/openai.py
utils/pruning.py
utils/questions.py

Managed to test and fixed a few edge cases
- we now pass args to `run_hf_eval` (standardize with other runners)
- we use `-d` as a boolean flag to opt in for private data. previous cli arg was faulty.
- fix openai runner to able to use private data
- update hf runner to use adapter if available
Verified that it runs with both openai and hf runners respectively:
**OA**
```
-q data/private_questions.csv \
-o results/private_questions.csv \
-g oa \
-d \
-f prompts/prompt.md \
-m gpt-3.5-turbo
/Users/jp/workspace/miniconda3/lib/python3.11/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
warn("The installed version of …
```

Various Fixes

---

.github/workflows/main.yml
eval/hf_runner.py
prompts/prompt.md
requirements.txt
tests/test_hf_runner.py
tests/test_utils_pruning.py
utils/pruning.py

- Use dynamic number of beams depending on the prompt's token length. We scale it down approximately quadratically due to the quadratic nature of attention. We now no longer need the statements to explicitly deal with torch memory before the generate statement.
- Update prompt to be the same as sql-coder.
- Add tests.
Verified that the latest fix is able to work with the following command:
```
-o "results/defog_sqlcoder_npl_short_stratified2_best.csv" \
-g hf \
-f prompts/prompt.md \
-m /home/defog/finetuning/starcoder/defog_sqlcoder_npl_short_stratified2/best
...
Correct so far: 145/200 (72.50%): 100%|█████████████████████████████████████████████████| 200/200 [08:49<00:00,  2.65s/it]
exact_match   correct
query_category …
```

Dynamic Beams

---

.gitignore
utils/pruning.py

Save embeddings for private and public data separately so that we wouldn't accidentally reference the wrong one when switching between the 2.

Save embeddings for private and public data separately

---

eval/vllm_runner.py
main.py
requirements.txt

Add runner with vllm.
We now give users the option to run their evals with vllm, which could be faster. vLLM supports batched generation which is much faster, and so we batch all of our queries at the start, and then verify the db correctness after all completions have been generated.
Tested with 4xA10's with a 34B CodeLlama derivative and it worked well with num_beams = 4, taking only 290s to generate completions for 200 questions. Total time taken (including model loading) was just over 6 mins.

Add vllm runner

---

README.md
eval/api_runner.py
main.py
prompts/prompt.md
query_generators/openai.py

This will be useful if - say - one wants to test multiple or inference strategies on a LLM that is hosted on a server. Currently, this can be used to send requests to a hosted vLLM server.
I tested this with `python main.py -g api -q data/questions_gen.csv -b 5 -f prompts/prompt.md --url MY_VLLM_SERVER_URL -o results/results.csv`

Added an option to let users make a call to any external API with a prompt

---

eval/api_runner.py
eval/hf_runner.py
eval/openai_runner.py
eval/vllm_runner.py
main.py
query_generators/openai.py
utils/pruning.py

Remove flag for public data. We now automatically infer whether db is public based on the name's membership in `defog_data.metadata.dbs`.
Tested with openai runner and vllm and both work. Tested vllm with a csv test dataset containing public and private dbs and it handled the running correctly.
```sh
$ python main.py \                        
-o results/my_query_generator.csv \
-g oa \
-f prompts/prompt_openai.md \
-m gpt-3.5-turbo-0613 \
-n 10 \
-p 5
preparing questions...
Correct so far: 9/10 (90.00%): 100%|█████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  3.16it/s]
exact_match  correct
query_category                      
date_functions          1.0      1.0
group_by                0.8      0.8 …
```

Removed public data flag

---

eval/api_runner.py
eval/openai_runner.py
eval/vllm_runner.py
prompts/README.md
prompts/prompt_instructions.md
prompts/prompt_openai.md
query_generators/openai.py
utils/pruning.py
utils/questions.py

The openai and vllm runner now passes in the instructions into the prompt if provided.
We provide a separate prompt for instructions as a drop in replacement for prompt.md when dealing with instructions based datasets.
openai runner works as before (3.5 without instructions):
```sg
-o results/my_query_generator.csv \
-g oa \
-f prompts/prompt_openai.md \
-m gpt-3.5-turbo-0613 \
-p 5
preparing questions...
Correct so far: 136/200 (68.00%): 100%|█████████████████████████| 200/200 [00:48<00:00,  4.09it/s]
exact_match   correct
query_category                       
date_functions     0.760000  0.760000
group_by           0.800000  0.800000
order_by           0.657143  0.742857
ratio              0.257143  0.342857
table_join         0.714286 …
```

Updated handling of instructions

---

eval/hf_runner.py

Modifies code for checking if beam search is enabled in #62. This ensures that the models doesn't wastes too much of the user's time by generating very long pieces of text in this test step.

Caps `max_new_tokens` in the beam search check

---

data/questions_gen_postgres.csv
data/questions_gen_snowflake.csv
eval/api_runner.py
eval/eval.py

Based on [Issue](https://github.com/defog-ai/sql-eval/issues/65)
- Clarified `How long has it been in days since the last admitted student?` to specify duration in days
- Removed ORDER_BY clause for `Which states border the state where lake ontario is?` since order does not matter
- Added word boundaries in normalize_table
- Removed redundant aggregate col `business.rating` from yelp and revised all queries with the removed col

Fixes based on issues raised by cfahlgren1

---

eval/vllm_runner.py

Tiny fix to make `vllm` based evals more robust

Added additional splitting on ``` substring in response parsing

---

data/questions_gen_postgres.csv
data/questions_gen_snowflake.csv
eval/eval.py
tests/test_eval.py

Previously, we found the logic of the `compare_df` function to fail at specific questions like the following:
```
name | num_publications 
------+------------------
ICML |                3
AAAS |                1
ISA  |                1
name | num_publications 
------+-------------------
ICML |                 3
ISA  |                 1
AAAS |                 1
```
The latter query should be considered correct since the question only requires the ordering of the `num_publications` column and not the `name` column. However, the `compare_df` function used to consider the latter query as incorrect. 
We have thus fixed this issue in the `normalize_table` function by first sorting rows by ORDER BY columns before sorting by the rest of the columns.
Mini note: We have also added a minor change …

Fixing normalize_table in compare_df

---

eval/eval.py
tests/test_eval.py

Earlier, the model would not consider these two results identical if they were for an `ORDER BY` question.
```
name | num_publications 
------+------------------
ICML |                3
AAAS |                1
ISA  |                1
```
```
name | publication_count 
------+-------------------
ICML |                 3
ISA  |                 1
AAAS |                 1
```
This PR fixes this issue. To test
```python
from eval.eval import normalize_table
import pandas as pd
df1 = pd.DataFrame([["ICML", 3], ["AAAS", 1], ["ISA", 1]], columns=["name", "num_publications"])
df2 = pd.DataFrame([["ICML", 3], ["ISA", 1], ["AAAS", 1]], columns=["name", "publication_count"])
normalize_table(df1, "order_by", "", "SELECT conference.name, COUNT(publication.pid) AS num_publications FROM publication JOIN …
```

Changes to sorting eval for increased robustness

---

eval/eval.py

Fixes an issue where `order_by_columns` is an empty list where REGEX has no matches and thus cause a `list index out of range`.
Thank you for all your contributions to open source :)

Order By Fix

---

README.md
eval/vllm_runner.py
main.py

Used this to test our private AWQ model. Works reasonably well! AWQ seems _much_ faster when running as an API for single use requests – though is slower than non-AWQ for batched processing. Also consumes just 1/4th the memory.
Side note: accuracy was reasonable. -3% compared to the non-AWQ version with the corresponding `num_beams` (tested for `num_beams` 4, 2, and 1).

add a quantized arg for vllm to run awq models

---

eval/anthropic_runner.py
eval/api_runner.py
eval/hf_runner.py
eval/openai_runner.py
eval/vllm_runner.py
prompts/README.md
prompts/prompt.md
prompts/prompt_anthropic.md
prompts/prompt_openai.md
query_generators/anthropic.py
query_generators/openai.py
query_generators/query_generator.py
utils/questions.py

- Modified files to incorporate glossary and table_metadata_strings if provided by the data files.
- If table_metadata_string is provided in the csv data file, pruning of metadata will not occur. This aids evaluation of queries independent of the pruning function.

Glossary & table metadata string

---

README.md
eval/llama_cpp_runner.py
main.py

We can now use `llama-cpp` and `llama-cpp-python` to run sql-eval.
To test with a q5 quant of `sqlcoder-7b-2`
```bash
python -W ignore main.py \
-db postgres \
-o "results/results.csv" \
-g llama_cpp \
-f "prompts/prompt.md" \
-m ~/.defog/sqlcoder-7b-q5_k_m.gguf
```
Additionally, if you would like to always report your results to an upload_url, even if it's not explicitly provided, you can now set it in your environment variables as `SQL_EVAL_UPLOAD_URL`

Add llama_cpp_runner.py for Llama CPP evaluation

---

README.md
eval/mlx_runner.py
main.py

This was tested on the amazing port of sqlcoder-7b-2 by @abhishek-ch on mlx-community [here](https://huggingface.co/mlx-community/defog-sqlcoder-7b-2)
`mlx-lm` does not support beam search yet – will update this to include beam search once it does (might make a pull request to `mlx-lm` to support beam search soon)
Additionally, this has `verbose=True` set up. We can choose to set that to `False`. Currently takes ~3-4 seconds per query on an M2 Max if your system is not on power saving mode.

Added an MLX runner for evals

---

README.md
eval/anthropic_runner.py
eval/api_runner.py
eval/gemini_runner.py
eval/hf_runner.py
eval/llama_cpp_runner.py
eval/mistral_runner.py
eval/mlx_runner.py
eval/openai_runner.py
eval/vllm_runner.py
main.py
query_generators/anthropic.py
query_generators/openai.py
tests/test_utils_pruning.py
utils/gen_prompt.py
utils/pruning.py

Added number of columns being pruned from metadata as an argument, alongside whether or not we want to shuffle the metadata.
Added a unit test for the new behaviour.
Tested on openai's gpt3.5/4, claude-3-opus, mistral-mediumm, gemini-pro, and api server and the results are meaningful.

Add number of columns and shuffle as args

---

eval/eval.py

Previously, the question `What's the average duration between departure and arrival times minus 34 minutes? Convert from UNIX to regular datetime.`, we always got a `'bool' object has no attribute 'all'` error
Using the traceback, it seems like the error was coming from this section of the code:
```
Traceback (most recent call last):
File "/Users/rishabh/defog/sql-eval/eval/api_runner.py", line 54, in process_row
exact_match, correct = compare_query_results(
File "/Users/rishabh/defog/sql-eval/eval/eval.py", line 348, in compare_query_results
if compare_df(
File "/Users/rishabh/defog/sql-eval/eval/eval.py", line 250, in compare_df
if df_gold.shape == df_gen.shape and (df_gold.values == df_gen.values).all():
AttributeError: 'bool' object has no attribute 'all'
```
This fixes this with …

handle exceptions when comparing dataframes with single value

---

README.md
eval/anthropic_runner.py
eval/api_runner.py
eval/eval.py
eval/gemini_runner.py
eval/hf_runner.py
eval/llama_cpp_runner.py
eval/mistral_runner.py
eval/mlx_runner.py
eval/openai_runner.py
eval/vllm_runner.py
main.py
tests/test_eval.py

Earlier, we could get mismatches with rounded floats. For example, in the example below, the 2 frames would not be considered equal
```python
import pandas as pd
from pandas.testing import assert_frame_equal
df1 = pd.DataFrame([[1,2.123,"abc"], [2, 3.123, "xyz"]])
df2 = pd.DataFrame([[1,2.1234,"abc"], [2, 3.1234, "xyz"]])
assert_frame_equal(df1, df2) # throws an error
```
However, there are instances where we want to specify a float rounding limit beyond which both values are considered equal. In `pandas`, can do this with `df.round(n)`, where `n` refers to the number of decimal points. The function takes care of only rounding floats, and not modifying `int`, `bool`, `object` columns
```python
import pandas as pd
from pandas.testing import assert_frame_equal
df1 = …
```

Enable argument for specifying how much to round floats to

---

eval/anthropic_runner.py
eval/api_runner.py
eval/gemini_runner.py
eval/hf_runner.py
eval/llama_cpp_runner.py
eval/mistral_runner.py
eval/mlx_runner.py
eval/openai_runner.py
eval/vllm_runner.py
main.py

- Added support for multiple question files in 1 evaluation for all runners. This allows us to generate completions for all questions with just 1x setup in the runner (instead of nx setup for each call to sql-eval/individual runners). Checks are now made in `main.py`, with each runner then iterating through the list of question/prompt/output file combinations. Supported combinations include:
- 1 question files, 1 prompt file, 1 output files
- n question files, 1 prompt file, n output files
- 1 question files, n prompt file, n output files
- n question files, n prompt file, n output files
- Increased max_tokens for vllm to 600.
Tested on vllm and runner:
```
Preparing /models/combined/sqlcoder_7b_bf16_r128_ds_002_750_b20/checkpoint-700
2024-04-17 09:37:09,387 INFO worker.py:1724 -- Started …
```

Enable multiple question files

---

eval/vllm_runner.py
gcs_eval.py

Add script for continuously pulling down newly saved models and evaluating them with the vllm runner.
You can run it in the background (via nohup/screen/tmux) with `python3 gcs_eval.py`, and it will continuously run this loop (checks every 10s):
- find new models that have been saved in `GCS_MODEL_DIR`
- download each new model into `LOCAL_MODEL_DIR`
- evaluate the new model and output the relevant csv file
- move the model from `GCS_MODEL_DIR` to `GCS_MODEL_EVAL_DIR`
Some things that don't work:
- calling `run_vllm_eval` directly within the loop as initializing the LLM with `vllm` will call `ray.init()`, which can only be called once per script, and will hang on subsequent calls.

Continuous eval script

---

eval/api_runner.py
eval/hf_runner.py
eval/vllm_runner.py
gcs_eval.py

Updates to runners:
API
* Made it take in an additional `-m` parameter that will help us tell the script which model's tokenizer to load
VLLM
* Enable batching. When set to `-bs 200` it reverts to original vllm generation behaviour/scores (see `[scores](https://docs.google.com/spreadsheets/d/1rkrhQmrpTWMNorrVQxM_KnHslKQiJDSs_kzxt6fmKbI/edit#gid=736994119)`).
HF
* Token(izer) updates
Also fixed a small edge case for the `gcs_eval.py` script where it was reading/processing empty lines

Update model runners

---

eval/api_runner.py

This is to ensure that the api runner can be easily used on machines where a tokenizer has not yet been downloaded, or `transformers`

Remove dependency on AutoTokenizer in api_runner

---

eval/hf_runner.py
gcs_eval.py

Fix temperature/top_p warnings by setting it explicitly when generating
Add batch_size param to gcs_eval.py
Tested with the following and the warnings don't show up anymore:
```
python3 main.py \
-db postgres \
-q data/instruct_basic_postgres.csv data/instruct_advanced_postgres.csv data/questions_gen_postgres.csv \
-o "results/${model_name}_beam1_basic_hf.csv" "results/${model_name}_beam1_advanced_hf.csv" "results/${model_name}_beam1_v1_hf.csv" \
-g hf \
-b 1 \
-c 0 \
-f "prompts/prompt.md" \
-m "${model_name}"
```

fix temperature/top_p warning

---

README.md
eval/bedrock_runner.py
main.py

To run this, we can go 
```bash
python -W ignore main.py \
-db postgres \
-q "data/questions_gen_postgres.csv" \
-o results/llama3_70b.csv \
-g bedrock \
-f prompts/prompt.md \
-m meta.llama3-70b-instruct-v1:0 \
-p 5
Correct so far: 147/200 (73.50%): 100%|███████████████████████████████████████████████████| 200/200 [02:42<00:00,  1.23it/s]
correct  error_db_exec
query_category                         
date_functions  0.680000       0.200000
group_by        0.828571       0.000000
instruct        0.771429       0.114286
order_by        0.885714       0.000000
ratio           0.342857       0.114286
table_join      0.885714       0.000000
```

Added a bedrock runner to make it easier to run models straight from bedrock

---

README.md
eval/api_runner.py
main.py

Enable testing of inference using TGI via the api runner.
We only need to change the way the request parameters are formatted, and facilitate this simple switching via the new flag `--api_type`
Updated README to show how to use it.

Enable tgi via api type

---

CONTRIBUTING.md
README.md

I noticed that there was a mistake in the install step. In order to install deps, you would need to first clone the repository, as you otherwise would not have access to the `requirements.txt` file.
I therefore restructuring the installation instructions to follow a more natural flow and updated the corresponding text.
I am also used to the same installation steps being part of the `CONTRIBUTING.md` markdown, which I believe is quite standard. When making my initial PR, I failed to see that I needed to download the `NER heuristic`, which caused tests to fail. This could have been resolved by having these steps in the contrib markdown directly, as this is what I followed when making the PR.

Added install step to CONTRIBUTING.md; refactoring install step in README

---

gcs_eval_checkpoints.py

Added a script like `gcs_eval.py` but for working with nested folders of weights, for example:
```
models/
├── model1/
│   ├── checkpoint-500/ # contains the safetensors
│   └── checkpoint-1000/
└── model2/
├── checkpoint-500/
└── checkpoint-1000/
```
We keep the original `gcs_eval.py` around for users who want to work with non-nested folders of weights, for example:
```
models/
├── model1/ # contains the safetensors
└── model2/
```
For context, you can run this script `python3 gcs_eval.py` and it will continuously pull models from gcs, eval it (outputting the results/csv locally), and then shift the evaluated model into a different directory on gcs.

gcs eval for checkpoint weights

---

gcs_eval_checkpoints.py

- Updated gcs_eval_checkpoints.py to save tokenizer if it is missing from checkpoint directory
- Fixed wrong directory when moving to eval folder. Previously it would save model weights into `checkpoint-xxx` and not `run_name/checkpoint-xxx` within `GCS_MODEL_EVAL_DIR`. We now fix it to save to `run_name/checkpoint-xxx`

Eval script fixes

---

eval/eval.py

We would silently fail and hide the exceptions whenever the environment doesn't have psycopg/psycopg2 installed. This doesn't usually happened on a machine that has our usual setup with everything pre-installed, but could happen in new environments or on other users' environments. We make the error handling/messages more explicit so that people know if there's an error and how to remedy.

Improve psycopg dialect string handling

---

utils/api_server.py

Problem: we were implicitly adding another bos token inside the vllm engine (in addition to the one in the prompt). This caused double bos tokens for our prompts during evaluation and a slight degradation.
Solution: Modify our api_server.py to ensure that we don't create double bos tokens by not adding special tokens (bos/eos) during the token encoding and only add the bos if it's missing after. We preferred modifying it in the api_server.py to avoid having to specify the tokenizer for api server runs and customizing the prompt based on the model/tokenizer revision.
Alternative considered: Modify api runner to pass in the prompt_token_ids directly. However, this would not have broader compatibility with the open ai server formats, or with the vanilla api server from vllm, since those only …

Api server updates

---

eval/vllm_runner.py
run_checkpoints.sh

small changes to vllm runner:
- changed tensor parallelism to 1 always (ie disabled) as we generally saw better results [here](https://docs.google.com/spreadsheets/d/1wDkn4IsXyVUOyJrfY1BQMfeFExt872vmoHflv09Nnlc/edit#gid=0)
- remove tqdm from vllm's `.generate` as it was cluttering up the output.
also added a simple script for evaluating checkpoints in a directory sequentially.

small changes to vllm runner

---

run_checkpoints.sh
utils/api_server.py
utils/dialects.py

- api server to not print prompt token ids
- postpone imports in dialects.py to avoid importing unless we're using the specific db_type and actually triggering the validity checks

Usability improvements

---

eval/api_runner.py
translate_sql_dialect.py
utils/dialects.py

Small fixes:
- Replaced SERIAL data type for sqlite ddl statements as it's not a valid data type
- Drop valid and err_msg columns in final df for translation if we're sure that there are no invalid rows that need manual correction
- Edited printed path for where logprobs are stored

SQLite SERIAL, drop valid/err_msg cols

---

eval/api_runner.py
eval/eval.py

- Removed spaces before brackets post sql generation as MySQL cannot parse with the additional spaces
- Fixed a persistent T-SQL exec error stemming from `query_tsql_db` that would not form the dataframe due to shape mismatch.
- Fixed process_row to include keys `tokens_used` and `logprobs` when post request times out. Previously it would produce NaNs in the final json file, which could not be read by the eval_visualizer.

Small pesky bugs found while examining dialect exec errors

---

README.md
eval/api_runner.py
eval/bedrock_runner.py
eval/eval.py
eval/gemini_runner.py
eval/hf_runner.py
eval/llama_cpp_runner.py
eval/mistral_runner.py
eval/mlx_runner.py
eval/vllm_runner.py
main.py
prompts/prompt_cot.md
utils/gen_prompt.py
utils/questions.py

This automatically generates relevant table aliases and appends it to a prompt. Doing so transfers the onus of creating table aliases away from the LLM. We _may_ have to retrain our LLM to expect this kind of prompting, so that it expects a more varied source of inputs.
Here's an example of how to run this.
```bash
python main.py \
-db postgres \
-q "data/questions_gen_postgres.csv" "data/instruct_basic_postgres.csv" "data/instruct_advanced_postgres.csv" "data/idk.csv" \
-o results/classic_new_reprompt.csv results/basic_new_reprompt.csv results/advanced_new_reprompt.csv results/idk_new_reprompt.csv \
-g api \
-b 1 \
-f prompts/prompt_cot.md \
--api_url "YOUR_API_ENDPOINT" \
--api_type "vllm" \
-p 10 \
-c 0 --logprobs --cot_table_alias
```

Dynamically add table aliases without an LLM + de-duplicate columns in pandas

---

utils/gen_prompt.py
utils/pruning.py

- Edited logic of metadata retrieval, such that translation still takes place even if columns_to_keep > 0 (simply shifted the if/else logic)
- Also fixed pruning code such that it still works with translation. Previously it had issues splitting data types with commas e.g. `numeric(10,5)` as well as tables that included schema names e.g. `consumer_div.wallet_transactions_daily`. These issues led to the incorrect retrieval of metadata, resulting in error execs in sql-eval.

Fix pruning and the logic of md retrieval

---

README.md
run_checkpoints.sh
run_checkpoints_cot.sh
utils/questions.py

Add `prealias` option to `--cot_table_alias`. The difference from the existing `instruct` option is that `instruct` will get the model to generate the chain-of-thought table aliases, while `prealias` would already generate the aliases in the prompt.

Add prealias option

---

upload_wandb.ipynb

Added notebook for uploading vllm eval results to wandb post-hoc.
This notebook will take the results produced by `run_checkpoints.sh` and `run_checkpoints_cot.sh` and upload them to the specified run id on wandb.
There is 1 weird quirk about wandb where they don't allow you to log to past steps once completed (see [forum post](https://community.wandb.ai/t/wandb-log-inconsistent-behavior-with-step-parameter/2771)). To work around that, we just continue logging from the latest step onwards (which will cause our steps displayed on wandb to be inconsistent with the actual checkpoints, but should be sufficient for comparison reasons).
See screenshot below:

Upload wandb results

---

eval/gemini_runner.py
eval/mistral_runner.py
query_generators/anthropic.py
query_generators/openai.py
tests/test_utils_pruning.py
utils/dialects.py
utils/gen_prompt.py
utils/pruning.py

- Modify `get_md_emb` to split the ddl statements from the join string so as to faciliate translations. (Join strings don't have to be translated)
- Changed tests and affected runners accordingly
- Remove tildes in sql before translation as sqlglot cannot parse them
- Exclude comments from formatting of reserved keywords

Modify pruning and translation funcs

---

.gitignore
utils/api_server.py

Updated api server to pass in the prompt token ids in the right format depending on the vllm version.
Tested with version [0.5.0.post1](https://github.com/vllm-project/vllm/releases/tag/v0.5.0.post1), which I upgraded locally in my runpod instance and it works (with the usual `run_checkpoints_cot.sh` script).

VLLM version support

---

README.md
eval/api_runner.py
eval/vllm_runner.py
utils/api_server.py

- LoRA adapters can now be used with vLLM on top of a base model in `api_runner.py` and `vllm_runner.py`.
- Note that for now LoRA ranks must be one of (8, 16, 32, 64)

LoRA support for vLLM

---

prompts/prompt_cot.md
run_checkpoints_adapters.sh
translate_sql_dialect.py
utils/dialects.py
utils/gen_prompt.py

- Previously, schema names could still be found in the instructions of sqlite, mysql, bigquery. Script will now scrub these.
- Fixed `ddl_to_dialect` which had redundant preprocessing that was accidentally removing some column descriptions. 
- Preserved new lines in translated ddl with the arg `pretty=True`
- Removed schema names from cot_instructions if one of the 3 dialects above.
- Also changed model for translation to gpt-4-turbo. Hopefully it can correct the date arithmetic translations in #172
- Minor: took the chance to modify a print statement in run_checkpoints_adapters

Fix translation script

---

eval/api_runner.py
main.py

Added args.adapter_name for use only together with production server. 
Using adapter paths (args.adapter) is still more convenient for testing with sql-eval

Add adapter_name arg

---

utils/api_server.py

- Pop sql_lora_name param which is not used in the api_server within sql-eval. The param is only used when making requests to the production server.

Pop sql_lora_name

---

README.md
eval/together_runner.py
main.py
prompts/prompt_together.json
requirements.txt
utils/gen_prompt.py
utils/questions.py

- Add runner for together.ai's API. Quite similar to `bedrock_runner.py`
- Extended `generate_prompt.py` to take in json files, where we have a list of messages with `role` and `content`. This returns a list of messages (dict) for the `messages` parameter in the [openai create chat completions api](https://platform.openai.com/docs/api-reference/chat/create).
- Add table aliases as a different field `table_aliases` in the main dataframe, as `cot_instructions` is a more general and experimental field (e.g. for reasoning etc). We get `prompt_together.json` to read off the `table_aliases` field instead of using `cot_instructions`.
Ran the full evaluation over `meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo` as follows:
```sh
python3 main.py \
-db postgres \
-q data/instruct_basic_postgres.csv …
```

Together.ai Runner

---

README.md
eval/api_runner.py
main.py
prompts/prompt_cot.md
prompts/prompt_cot_postgres.md
prompts/prompt_cot_sqlite.md
utils/gen_prompt.py
utils/questions.py

- Replaced `cot_instructions` with `table_aliases`. We prefer to leave `cot_instructions` as an experimental field.
- Users can insert `table_aliases` into their prompts more easily now by just directly sticking the placeholder `{table_aliases}` inside their prompt, without having to pass a combination of cli args + prompt changes + code changes.
- Rename `join_hints` to `join_str` to better match the variable name
We ran the following on gpu-inference
```
./run_model_cot.sh defog/sqlcoder-8b-dare-ties
```
Results:
| Question File                     | Accuracy |
|-----------------------------------|----------|
| instruct_basic_postgres.csv       | 92.50%   |
| instruct_advanced_postgres.csv    | 81.25%   |
| questions_gen_postgres.csv        | 83.81%   |
These are the same compared to …

Clean up cot_instructions placeholder

---

README.md
eval/openai_runner.py
prompts/prompt_openai_o1.json
query_generators/openai.py
requirements.txt

Support evaluation of latest openai o1-* models. We branch out the code paths in the openai query generator by checking if the model is from the `o1-` family, as the o1 model doesn't support some parameters currently.
Tested o1-mini model:
```
-db postgres \
-q "data/questions_gen_postgres.csv" "data/instruct_basic_postgres.csv" "data/instruct_advanced_postgres.csv" \
-o results/openai_o1mini_classic.csv results/openai_o1mini_basic.csv results/openai_o1mini_advanced.csv \
-g oa \
-f prompts/prompt_openai_o1.json \
-m o1-mini \
-p 1 \
-t 120 \
-c 0
```
(works, still running)
Previous gpt-4o request still works:
```
-db postgres \
-q "data/questions_gen_postgres.csv" "data/instruct_basic_postgres.csv" "data/instruct_advanced_postgres.csv" \
-o …
```

Update openai runners

---

eval/api_runner.py

The eval I ran earlier had a lot of errors because of this space before  and after `(` and `)`.
This is something that is completely fine with postgres but erroneous in mysql. We do some post cleaning of the query to make sure we get rid of any such spaces. A case with spaces both before and after a bracket was handled but a more popular case is when there is a space after the bracket. Including this in the `clean_generated_query` for clarity.

Added mysql case in cleaner

---

.github/workflows/main.yml
requirements.txt
requirements_test.txt
run_model_cot.sh
tests/test_utils_pruning.py
utils/api_server.py

- update api_server to be compatible with latest version of vllm
- removed deprecated param `cot_table_alias` from `run_model_cot.sh`
Tested with:
```
./run_model_cot.sh defog/sqlcoder-8b-dare-ties
```
Results changed slightly due to running on an A40 with more memory, but overall still similar to past runs:
| Model                  | sqlcoder-8b-dare-ties |
|------------------------|-----------------------|
| V1 Accuracy            | 88.10%                |
| Basic Accuracy         | 100%                  |
| Advanced Accuracy      | 90.62%                |
| Overall Accuracy       | 90.1%                 |

VLLM Compatibility Update

---

README.md
eval/deepseek_runner.py
main.py
requirements_test.txt

We add a deepseek runner to support evaluating deepseek models via their official API.
To verify that this works
```bash
python main.py \      
-db postgres \
-q "data/questions_gen_postgres.csv" "data/instruct_basic_postgres.csv" "data/instruct_advanced_postgres.csv" \
-o results/deepseek_classic.csv results/deepseek_basic.csv results/deepseek_advanced.csv \
-g deepseek \
-f prompts/prompt_openai.json \
-m deepseek-chat \
-p 5 \
-c 0
```
**For v1**
```
Correct so far: 188/210 (89.52%)
correct  error_db_exec
query_category                         
date_functions  0.800000       0.028571
group_by        1.000000       0.000000
instruct        0.914286       0.000000
order_by        0.914286       0.000000
ratio           0.771429       0.057143
table_join      0.971429       0.000000
``` …

Add support for deepseek models
